#!/bin/bash
# This is a simple build script and will be executed on your CI system if
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.
if [ ! -e $OPENSHIFT_DATA_DIR/bin/pip ]; then
	pushd $OPENSHIFT_TMP_DIR
	wget http://pypi.python.org/packages/source/p/pip/pip-1.1.tar.gz
	tar zxf pip-1.1.tar.gz
	cd pip-1.1
	$OPENSHIFT_DATA_DIR/bin/python setup.py install
	popd
fi
PATH=$PATH:$OPENSHIFT_REPO_DIR/lib64/R
export PATH
pip install rpy2
