#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
#export LD_LIBRARY_PATH=${OPENSHIFT_REPO_DIR}lib64/R/lib:$LD_LIBRARY_PATH
#export LD_LIBRARY_PATH=/var/lib/openshift/516d804c5973caab10000001/app-root/runtime/repo/lib64/R/lib:/var/lib/openshift/516d804c5973caab10000001/python-3.3/opt/lib
#export LD_PRELOAD=$LD_LIBRARY_PATH
